sound:
  enabled: true
  sound: ENTITY_FIREWORK_ROCKET_LAUNCH
  volume: 1.0
  pitch: 1.0
particle:
  enabled: true
  particle: VILLAGER_HAPPY
  # The amount of particles to spawn
  amount: 1
  # The delay between particles in ticks (20 ticks = 1 second)
  delay: 5
  # Instead of spawning particles when player is going upwards, do set amount of iterations
  iterations:
    enabled: false
    amount: 5
signYOffset: -2
falldamage:
  # Should the plugin prevent fall damage?
  prevent: true
  # Time multiplier for fall damage prevention
  # Only change this if you're experiencing issues with fall damage
  multiplier: 1.255